### PR TITLE
Release: 3.0.0-beta.2

### PR DESCRIPTION
**Pull request by jcvenegas**
Update release version according to new Clear Containers release.

Fixes: #113

Signed-off-by: Jose Carlos Venegas Munoz <jose.carlos.venegas.munoz@intel.com>

### CODE REVIEW

**Comment by chavafg** [comment]
the unit tests work well with Go 1.9, maybe travis is using a newer version of Go for the `Go:tip`
Is there anyway we can disable that version for our checks?

**Comment by sboeuf** [comment]
@chavafg disabling this version check is easy, you just need to remove this line https://github.com/clearcontainers/proxy/blob/master/.travis.yml#L6
The question is more about, do we want to remove this version check ? @grahamwhaley @sameo @egernst @jodh-intel @mcastelino any thought on that ?

**Comment by sboeuf** [comment]
@jcvenegas Nice that you found how to fix the go tip issue, but please submit a separate PR for that. We're gonna merge it first and then we'll be able to merge the beta2 release PR.

**Comment by jcvenegas** [comment]
@sboeuf  created PR #116  after is merged please rerun travis in this PR.

**Comment by sboeuf** [comment]
I can't cause I don't have the super power on this repo.We need @amshinde @sameo @mcastelino or @grahamwhaley to be able to merge this one.
After this will be merged (probably in a few hours), you'll be able to rebase this PR and the CI should be happy (hopefully).

**Comment by jodh-intel** [comment]
It might be worth blocking this on #29 since the `VERSION` string isn't required (atleast assuming you have a `git` checkout).

**Pull request merged**
