### PR TITLE
Proxy Emancipation

### PR DESCRIPTION
**Pull request by dlespiau**
This PR adds the basic dev/CI environment for the proxy now that it has been 

- Make file with build/check/install targets
- travis CI integration
- vendoring
- a few fixups due to splitting the proxy out of the cc-oci-runtime repo

### CODE REVIEW

**Comment by dlespiau** [comment]
PR updated:

- Added coveralls support

**Comment by dlespiau** [comment]
PR updated:

- Add a doc Makefile target that displays godoc in the browser
- Add a coverage Makefile target that displays nicely formatted coverage info in the browser

**Comment by sameo** [comment]
LGTM

**Comment by dlespiau** [comment]
Thanks! Merging this, no functional changes really, just triavial-ish maintenance work.

**Pull request merged**
