### PR TITLE
logging improvements, 1st pass

### PR DESCRIPTION
**Pull request by dlespiau**
I have more things in the pipeline but it's Friday and this PR has a few interesting fixes include a fix for the awful qemu logging (extra lines) caused by the port to logrus.

### CODE REVIEW

**Comment by jodh-intel** [comment]
lgtm

**Comment by sboeuf** [comment]
LGTM

**Comment by dlespiau** [comment]
@amshinde just missing your review for this one.

**Comment by amshinde** [comment]
lgtm

**Pull request merged**
