### PR TITLE
Update docs to replaces hyperstart references with agent.

### PR DESCRIPTION
**Pull request by amshinde**

### CODE REVIEW

**Comment by jodh-intel** [comment]
lgtm

**Comment by amshinde** [comment]
@iphutch Can you take a look at this?

**Comment by amshinde** [comment]
@grahamwhaley Can you merge this one?

**Comment by jodh-intel** [comment]
lgtm

**Comment by sameo** [comment]
LGTM

**Comment by grahamwhaley** [comment]
Just a note - we should do this as well:
https://github.com/clearcontainers/proxy/blob/master/docs/high-level-overview.png

The source for that png I believe can be found in:
https://github.com/clearcontainers/runtime/blob/master/docs/architecture/architecture-diagrams.odp
or used to (you may have to dig up an older rev. if it has been replaced etc.).

**Pull request merged**
