### PR TITLE
Remove redundant "if" checks

### PR DESCRIPTION
**Pull request by WeiZhang555**
Signed-off-by: Zhang Wei <zhangwei555@huawei.com>

### CODE REVIEW

**Comment by WeiZhang555** [comment]
These issues are detected by a latest golint, gometalinter didn't detect this is maybe because gometalinter is using an old golint tool :smile: 
Solve it whatever as I've already noticed this.

**Comment by jodh-intel** [comment]
lgtm

**Comment by sboeuf** [comment]
LGTM

**Comment by sboeuf** [comment]
@amshinde please take a look !

**Pull request merged**
