### PR TITLE
pullapprove: Require documentation team approval

### PR DESCRIPTION
**Pull request by sameo**
For all documentation files.

Signed-off-by: Samuel Ortiz <sameo@linux.intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
lgtm

**Comment by sboeuf** [comment]
LGTM

**Comment by dlespiau** [comment]
I'm not too sure we need to gate *every* change to md files with the ack from the documentation team, that adds both delay and burden on already stretched individuals. Oh well.

lgtm

**Comment by sboeuf** [comment]
@dlespiau I agree about the latency this will introduce. I think the easiest way to go away with that is to submit a PR for code changes only, and then you can submit a PR to update the readme. That way, you don't care if it takes some time to get the documentation's PR merged.

**Comment by grahamwhaley** [comment]
@sboeuf I'm not sold on the split PR idea - that could mean the code and the docs get out of sync, and that is bad. If we do find there is a problem with getting the docs processed then I think it would be better we find another way of fixing that.

**Comment by jodh-intel** [comment]
I agree with @grahamwhaley. Honestly, how many PRs have we absolutely had to land "immediately" or the world will end?

If a developer is impatient to use some pending PR code, they can merge it into their branch and keep working.

Absolute worst case, we temporarily disable pullapprove.

**Comment by sameo** [comment]
This is just a pullapprove change away. If this proves to be ineffective, we can disable that at will. I trust the documentation team latency will be low enough.

**Comment by sboeuf** [comment]
@jodh-intel it is not about the world ending but more about the eternal rebase of a PR that is ready, but not ready for the doc.

**Pull request merged**
