### PR TITLE
Add a --version flag

### PR DESCRIPTION
**Pull request by dlespiau**

### CODE REVIEW

**Comment by jodh-intel** [comment]
Once a comment has been added on `Version` to stop the linters bleating...

lgtm.

**Comment by dlespiau** [comment]
FWIW, coveralls lies, we never were at 82%+ coverage.

**Comment by jodh-intel** [comment]
maybe a Travis re-trigger will convince coveralls to allow this PR?

**Comment by dlespiau** [comment]
(triggered again, with no luck)

**Comment by jodh-intel** [comment]
Might be best to raise a new PR to re-trigger coveralls then.

Aside: I've noticed a lot of oddities with coveralls recently in the runtime repo. It might be time to see if there are any good alternatives.

**Comment by jodh-intel** [comment]
Could you try a new PR so we can get this merged for the next release?

**Pull request closed without merging**
