### PR TITLE
One proxy per vm

### PR DESCRIPTION
**Pull request by jodh-intel**
Allow the proxy to be run for a single pod.

This branch allows multiple proxies to be run on a single system, one per pod. Note that it also permits this behaviour even when the proxy is run as a system-level systemd service.

### CODE REVIEW

**Comment by jodh-intel** [comment]
Tested locally to ensure it is possible to run a system-level `cc-proxy` instance plus pod-level instances.

**Comment by sboeuf** [comment]
@jodh-intel oh ok so you mean with this patch, we can still use the proxy as a single instance ?

**Comment by jodh-intel** [comment]
Hi @sboeuf - yes, we can retain the systemd-spawned instance for the time being, then remove that functionality later. This multi-step process allows us to keep disruption to a minimum. See https://github.com/clearcontainers/runtime/issues/795.

**Comment by sboeuf** [comment]
@jodh-intel that's perfect to go step by step, I agree we don't want to break everyhting :)

**Comment by sboeuf** [comment]
LGTM

**Comment by sboeuf** [comment]
@amshinde please take a look and merge this so that we can move forward with https://github.com/containers/virtcontainers/pull/483

**Pull request merged**
