### PR TITLE
version: Fix version number

### LINKED ISSUE #99: mismatch between version showed by binary and packaged version
~# /usr/libexec/clear-containers/cc-proxy --version
Version: 3.0.0-alpha.1+
~# 
~# 
~# apt-get install cc-proxy
Reading package lists... Done
Building dependency tree       
Reading state information... Done
cc-proxy is already the newest version (3.0.0alpha.3+git.b73e4a3-0+3.1).
cc-proxy set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 5 not upgraded.

### PR DESCRIPTION
**Pull request by gorozco1**
Fixes version number mismatch

Fixes #99

Signed-off-by: Geronimo Orozco <geronimo.orozco@intel.com>

### CODE REVIEW

**Comment by gorozco1** [comment]
This will require a new tag after the merge

**Comment by jcvenegas** [comment]
@gorozco1 is it required that all components use the same version ?

**Comment by gorozco1** [comment]
@jcvenegas no is not required, but if we are going to merge this change we will need to tag a new release, since the merges and commits cannot be donde with a tag/release already shipped.

**Comment by amshinde** [comment]
@gorozco1 lets handle this with the next proxy release, that way we can add appropriate tag as well.

**Comment by gorozco1** [comment]
Closing in favor to be fixed in the next relase

**Pull request closed without merging**
