### PR TITLE
gometalinter

### PR DESCRIPTION
**Pull request by dlespiau**
gometalinter found a few interesting things in the proxy. Nothing really major but nice clean ups to have.

### CODE REVIEW

**Comment by devimc** [comment]
lgtm

**Comment by jodh-intel** [comment]
It would be better if the script sourced a config file to get the values for cyclomatic complexity and test deadline as that would allow the script to be replicated to the other repos which might have differing requirements. However, that's a nit and could be dealt with later, so,

lgtm

**Comment by sboeuf** [comment]
lgtm

**Comment by dlespiau** [comment]
(thanks for the lgtm, now need @amshinde  to approve).

**Comment by amshinde** [comment]
lgtm

**Pull request merged**
