### PR TITLE
vendor: Update virtcontainers vendoring

### PR DESCRIPTION
**Pull request by sboeuf**
This commit updates virtcontainers vendoring relying on version 0.7.0.

### CODE REVIEW

**Comment by jodh-intel** [comment]
lgtm

**Comment by dlespiau** [comment]
@sboeuf  that the go dep you have doesn't seem to do pruning (remove all the packages the proxy doesn't need from the vendoring directory). We always end up with the whole world but only depend on the hyperstart package (ciao-vendor was doing things right in that regard).

Good news though, it seems that pruning is now in go dep: https://github.com/golang/dep/blob/master/cmd/dep/prune.go. Worth trying to update your go dep?

**Comment by sboeuf** [comment]
@dlespiau let me try this right now.

**Comment by sboeuf** [comment]
@dlespiau go dep changed the way they manage the repo. It now expects a Gopkg.lock and a Gopkg.toml. This means we have to use `dep init` once again.
Does that sound okay to reset the vendoring ?

**Comment by dlespiau** [comment]
Sure, that's the downside of using an unstable tool, we were warned.

**Comment by sboeuf** [comment]
Sorry I thought it was more "stable" than this...

**Comment by sboeuf** [comment]
My bad, actually we can dep -update which adds new files and then we can prune. But note that prune does not remove the unused go files unfortunately.

**Pull request merged**
