### PR TITLE
release: Clear Containers 3.0.1

### PR DESCRIPTION
**Pull request by jcvenegas**
Version bump for Clear Containers 3.0.1

Fixes: #128

Signed-off-by: Jose Carlos Venegas Munoz <jose.carlos.venegas.munoz@intel.com>

### CODE REVIEW

**Comment by jcvenegas** [comment]
Jekinks just failed in unit tests, pasting here for reference.
```
00:09:04.240 === RUN   TestShimUsr1SignalProcessNotStarted
00:09:04.267 panic: test timed out after 2s
00:09:04.267 
00:09:04.267 goroutine 246 [running]:
00:09:04.267 testing.startAlarm.func1()
00:09:04.267 	/usr/local/go/src/testing/testing.go:1023 +0x139
00:09:04.267 created by time.goFunc
00:09:04.267 	/usr/local/go/src/time/sleep.go:170 +0x52
00:09:04.267 
00:09:04.267 goroutine 1 [chan receive]:
00:09:04.267 testing.(*T).Run(0xc42016a270, 0x9b909f, 0x23, 0x9c16c0, 0xc4200f5b01)
00:09:04.267 	/usr/local/go/src/testing/testing.go:698 +0x582
00:09:04.267 testing.runTests.func1(0xc42016a270)
00:09:04.267 	/usr/local/go/src/testing/testing.go:882 +0xab
00:09:04.267 testing.tRunner(0xc42016a270, 0xc4200f5c40)
00:09:04.267 	/usr/local/go/src/testing/testing.go:657 +0x108
00:09:04.267 testing.runTests(0xc42016e340, 0xbf3de0, 0x35, 0x35, 0x16)
00:09:04.267 	/usr/local/go/src/testing/testing.go:888 +0x4e1
00:09:04.267 testing.(*M).Run(0xc4200f5f28, 0x0)
00:09:04.267 	/usr/local/go/src/testing/testing.go:822 +0x1c4
00:09:04.267 github.com/clearcontainers/proxy.TestMain(0xc4200f5f28)
00:09:04.267 	/home/jenkins/go/src/github.com/clearcontainers/proxy/main_test.go:39 +0x1a4
00:09:04.267 main.main()
00:09:04.267 	github.com/clearcontainers/proxy/_test/_testmain.go:208 +0x341
00:09:04.268 
00:09:04.268 goroutine 17 [syscall, locked to thread]:
00:09:04.268 runtime.goexit()
00:09:04.268 	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1
00:09:04.268 
00:09:04.268 goroutine 35 [syscall]:
00:09:04.268 os/signal.signal_recv(0x4857e1)
00:09:04.268 	/usr/local/go/src/runtime/sigqueue.go:116 +0x104
00:09:04.268 os/signal.loop()
00:09:04.268 	/usr/local/go/src/os/signal/signal_unix.go:22 +0x30
00:09:04.268 created by os/signal.init.1
00:09:04.268 	/usr/local/go/src/os/signal/signal_unix.go:28 +0x4f
00:09:04.268 
00:09:04.268 goroutine 68 [select, locked to thread]:
00:09:04.268 runtime.gopark(0x9c21d8, 0x0, 0x9a97b8, 0x6, 0x18, 0x2)
00:09:04.268 	/usr/local/go/src/runtime/proc.go:271 +0xfd
00:09:04.268 runtime.selectgoImpl(0xc42009d750, 0xc42009d738, 0x0)
00:09:04.268 	/usr/local/go/src/runtime/select.go:423 +0x138a
00:09:04.268 runtime.selectgo(0xc42009d750)
00:09:04.268 	/usr/local/go/src/runtime/select.go:238 +0x1c
00:09:04.268 runtime.ensureSigM.func1()
00:09:04.268 	/usr/local/go/src/runtime/signal_unix.go:434 +0x1ea
00:09:04.268 runtime.goexit()
00:09:04.268 	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1
00:09:04.268 
00:09:04.268 goroutine 52 [chan receive]:
00:09:04.268 github.com/clearcontainers/proxy.startKSM.func1(0xc4201dc240, 0xc4201ce180)
00:09:04.268 	github.com/clearcontainers/proxy/_test/_obj_test/ksm.go:383 +0x6a
00:09:04.268 created by github.com/clearcontainers/proxy.startKSM
00:09:04.268 	github.com/clearcontainers/proxy/_test/_obj_test/ksm.go:386 +0x200
00:09:04.268 
00:09:04.268 goroutine 6 [select]:
00:09:04.268 github.com/clearcontainers/proxy.(*ksm).throttle.func1(0xc4201b0600)
00:09:04.268 	github.com/clearcontainers/proxy/_test/_obj_test/ksm.go:589 +0xb15
00:09:04.268 created by github.com/clearcontainers/proxy.(*ksm).throttle
00:09:04.268 	github.com/clearcontainers/proxy/_test/_obj_test/ksm.go:644 +0x14d
00:09:04.268 
00:09:04.268 goroutine 53 [select]:
00:09:04.268 github.com/clearcontainers/proxy.(*ksm).throttle.func1(0xc4201ce180)
00:09:04.268 	github.com/clearcontainers/proxy/_test/_obj_test/ksm.go:589 +0xb15
00:09:04.268 created by github.com/clearcontainers/proxy.(*ksm).throttle
00:09:04.268 	github.com/clearcontainers/proxy/_test/_obj_test/ksm.go:644 +0x14d
00:09:04.268 
00:09:04.268 goroutine 8 [chan receive]:
00:09:04.268 github.com/clearcontainers/proxy.startKSM.func1(0xc420010600, 0xc4201b0780)
00:09:04.268 	github.com/clearcontainers/proxy/_test/_obj_test/ksm.go:383 +0x6a
00:09:04.268 created by github.com/clearcontainers/proxy.startKSM
00:09:04.268 	github.com/clearcontainers/proxy/_test/_obj_test/ksm.go:386 +0x200
00:09:04.268 
00:09:04.268 goroutine 10 [chan receive]:
00:09:04.268 github.com/clearcontainers/proxy.startKSM.func1(0xc420010780, 0xc4201b0900)
00:09:04.268 	github.com/clearcontainers/proxy/_test/_obj_test/ksm.go:383 +0x6a
00:09:04.268 created by github.com/clearcontainers/proxy.startKSM
00:09:04.268 	github.com/clearcontainers/proxy/_test/_obj_test/ksm.go:386 +0x200
00:09:04.268 
00:09:04.268 goroutine 228 [IO wait]:
00:09:04.268 net.runtime_pollWait(0x7f034b5f7f78, 0x72, 0x4acc4a)
00:09:04.268 	/usr/local/go/src/runtime/netpoll.go:164 +0x5e
00:09:04.268 net.(*pollDesc).wait(0xc42034d568, 0x72, 0xbbc628, 0xffffffffffffffff)
00:09:04.268 	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x5b
00:09:04.268 net.(*pollDesc).waitRead(0xc42034d568, 0xc4203c32f4, 0xc)
00:09:04.268 	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x42
00:09:04.269 net.(*netFD).Read(0xc42034d500, 0xc4203c32f4, 0xc, 0xc, 0x0, 0xbbfbc0, 0xbbc628)
00:09:04.269 	/usr/local/go/src/net/fd_unix.go:250 +0x22b
00:09:04.269 net.(*conn).Read(0xc42015c3a8, 0xc4203c32f4, 0xc, 0xc, 0x1, 0xc4203c32f4, 0x0)
00:09:04.269 	/usr/local/go/src/net/net.go:181 +0x97
00:09:04.269 net.(*UnixConn).Read(0xc42015c3a8, 0xc4203c32f4, 0xc, 0xc, 0xc, 0xc, 0xc4201fdae0)
00:09:04.269 	<autogenerated>:143 +0x73
00:09:04.269 github.com/clearcontainers/proxy/api.ReadFrame(0x7f034b5f8060, 0xc42015c3a8, 0xc42015c3a8, 0x7f034b5f8060, 0xc42015c3a8)
00:09:04.269 	/home/jenkins/go/src/github.com/clearcontainers/proxy/api/protocol.go:94 +0xaf
00:09:04.269 github.com/clearcontainers/proxy/client.(*Client).sendCommandFull(0xc4203c3310, 0x0, 0x90aa40, 0xc4203ea320, 0x1, 0xc4201fdcd0, 0x436aa8, 0x50)
00:09:04.269 	github.com/clearcontainers/proxy/client/_obj/client.go:73 +0x1cf
00:09:04.269 github.com/clearcontainers/proxy/client.(*Client).sendCommand(0xc4203c3310, 0x0, 0x90aa40, 0xc4203ea320, 0x0, 0x0, 0xc4203c3310)
00:09:04.269 	github.com/clearcontainers/proxy/client/_obj/client.go:122 +0x7b
00:09:04.269 github.com/clearcontainers/proxy/client.(*Client).RegisterVM(0xc4203c3310, 0x9ac324, 0xa, 0xc4203439a0, 0x20, 0xc4203439e0, 0x20, 0xc4201fdea8, 0xc40000001a, 0xc4203c3310, ...)
00:09:04.269 	github.com/clearcontainers/proxy/client/_obj/client.go:196 +0x1a7
00:09:04.269 github.com/clearcontainers/proxy.(*testRig).RegisterVM(0xc42034d340, 0xc42034d340, 0xc420025300)
00:09:04.269 	/home/jenkins/go/src/github.com/clearcontainers/proxy/proxy_test.go:148 +0x1b9
00:09:04.269 github.com/clearcontainers/proxy.testShimSignalProcessNotStarted(0xc42033bc70, 0xa, 0x1)
00:09:04.269 	/home/jenkins/go/src/github.com/clearcontainers/proxy/proxy_test.go:783 +0x72
00:09:04.269 github.com/clearcontainers/proxy.TestShimUsr1SignalProcessNotStarted(0xc42033bc70)
00:09:04.269 	/home/jenkins/go/src/github.com/clearcontainers/proxy/proxy_test.go:816 +0x47
00:09:04.269 testing.tRunner(0xc42033bc70, 0x9c16c0)
00:09:04.269 	/usr/local/go/src/testing/testing.go:657 +0x108
00:09:04.269 created by testing.(*T).Run
00:09:04.269 	/usr/local/go/src/testing/testing.go:697 +0x544
00:09:04.269 
00:09:04.269 goroutine 224 [IO wait]:
00:09:04.269 net.runtime_pollWait(0x7f034b5f7738, 0x72, 0x4acc4a)
00:09:04.269 	/usr/local/go/src/runtime/netpoll.go:164 +0x5e
00:09:04.269 net.(*pollDesc).wait(0xc4203c8618, 0x72, 0xbbc628, 0xffffffffffffffff)
00:09:04.269 	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x5b
00:09:04.269 net.(*pollDesc).waitRead(0xc4203c8618, 0xc4203ad200, 0x8)
00:09:04.269 	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x42
00:09:04.269 net.(*netFD).Read(0xc4203c85b0, 0xc4203ad200, 0x8, 0x200, 0x0, 0xbbfbc0, 0xbbc628)
00:09:04.269 	/usr/local/go/src/net/fd_unix.go:250 +0x22b
00:09:04.269 net.(*conn).Read(0xc4200948a8, 0xc4203ad200, 0x8, 0x200, 0xc42021ee78, 0x436aa8, 0x0)
00:09:04.269 	/usr/local/go/src/net/net.go:181 +0x97
00:09:04.269 net.(*UnixConn).Read(0xc4200948a8, 0xc4203ad200, 0x8, 0x200, 0x200, 0x200, 0x1)
00:09:04.269 	<autogenerated>:143 +0x73
00:09:04.269 github.com/clearcontainers/proxy/vendor/github.com/containers/virtcontainers/pkg/hyperstart.ReadCtlMessage(0xbc5340, 0xc4200948a8, 0x0, 0x0, 0x0)
00:09:04.269 	/home/jenkins/go/src/github.com/clearcontainers/proxy/vendor/github.com/containers/virtcontainers/pkg/hyperstart/hyperstart.go:311 +0x120
00:09:04.269 github.com/clearcontainers/proxy/vendor/github.com/containers/virtcontainers/pkg/hyperstart.startCtlMonitor.func1(0xc4203c4820, 0xc42032d3e0)
00:09:04.269 	/home/jenkins/go/src/github.com/clearcontainers/proxy/vendor/github.com/containers/virtcontainers/pkg/hyperstart/multicast.go:55 +0x5c
00:09:04.269 created by github.com/clearcontainers/proxy/vendor/github.com/containers/virtcontainers/pkg/hyperstart.startCtlMonitor
00:09:04.269 	/home/jenkins/go/src/github.com/clearcontainers/proxy/vendor/github.com/containers/virtcontainers/pkg/hyperstart/multicast.go:69 +0x1f4
00:09:04.269 
00:09:04.269 goroutine 233 [IO wait]:
00:09:04.269 net.runtime_pollWait(0x7f034b5f7678, 0x72, 0x4acc4a)
00:09:04.269 	/usr/local/go/src/runtime/netpoll.go:164 +0x5e
00:09:04.269 net.(*pollDesc).wait(0xc42034d648, 0x72, 0xbbc628, 0xffffffffffffffff)
00:09:04.269 	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x5b
00:09:04.270 net.(*pollDesc).waitRead(0xc42034d648, 0xc4203a0470, 0x8)
00:09:04.270 	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x42
00:09:04.270 net.(*netFD).Read(0xc42034d5e0, 0xc4203a0470, 0x8, 0x8, 0x0, 0xbbfbc0, 0xbbc628)
00:09:04.270 	/usr/local/go/src/net/fd_unix.go:250 +0x22b
00:09:04.270 net.(*conn).Read(0xc42015c3c8, 0xc4203a0470, 0x8, 0x8, 0x100000002, 0x100000000000001, 0x100000001)
00:09:04.270 	/usr/local/go/src/net/net.go:181 +0x97
00:09:04.270 net.(*UnixConn).Read(0xc42015c3c8, 0xc4203a0470, 0x8, 0x8, 0x0, 0x0, 0x0)
00:09:04.270 	<autogenerated>:143 +0x73
00:09:04.270 github.com/clearcontainers/proxy/vendor/github.com/containers/virtcontainers/pkg/hyperstart/mock.(*Hyperstart).readCtl(0xc420214d80, 0xc4203a0470, 0x8, 0x8, 0x8, 0x8)
00:09:04.270 	/home/jenkins/go/src/github.com/clearcontainers/proxy/vendor/github.com/containers/virtcontainers/pkg/hyperstart/mock/hyperstart.go:185 +0xad
00:09:04.270 github.com/clearcontainers/proxy/vendor/github.com/containers/virtcontainers/pkg/hyperstart/mock.(*Hyperstart).readMessage(0xc420214d80, 0xc4203366e0, 0x46273c, 0xc4202ff128, 0xc4203366f8, 0xc420336728, 0x42880d)
00:09:04.270 	/home/jenkins/go/src/github.com/clearcontainers/proxy/vendor/github.com/containers/virtcontainers/pkg/hyperstart/mock/hyperstart.go:202 +0xa3
00:09:04.270 github.com/clearcontainers/proxy/vendor/github.com/containers/virtcontainers/pkg/hyperstart/mock.(*Hyperstart).handleCtl(0xc420214d80)
00:09:04.270 	/home/jenkins/go/src/github.com/clearcontainers/proxy/vendor/github.com/containers/virtcontainers/pkg/hyperstart/mock/hyperstart.go:237 +0x54
00:09:04.270 created by github.com/clearcontainers/proxy/vendor/github.com/containers/virtcontainers/pkg/hyperstart/mock.(*Hyperstart).Start.func1
00:09:04.270 	/home/jenkins/go/src/github.com/clearcontainers/proxy/vendor/github.com/containers/virtcontainers/pkg/hyperstart/mock/hyperstart.go:374 +0xb5
00:09:04.270 
00:09:04.270 goroutine 225 [runnable]:
00:09:04.270 github.com/clearcontainers/proxy/vendor/github.com/containers/virtcontainers/pkg/hyperstart.(*multicast).processBufferedReply(0xc4203c4820, 0xc42032d440)
00:09:04.270 	/home/jenkins/go/src/github.com/clearcontainers/proxy/vendor/github.com/containers/virtcontainers/pkg/hyperstart/multicast.go:120
00:09:04.270 created by github.com/clearcontainers/proxy/vendor/github.com/containers/virtcontainers/pkg/hyperstart.(*multicast).listen
00:09:04.270 	/home/jenkins/go/src/github.com/clearcontainers/proxy/vendor/github.com/containers/virtcontainers/pkg/hyperstart/multicast.go:158 +0x1f9
00:09:04.270 
00:09:04.270 goroutine 232 [runnable]:
00:09:04.270 github.com/clearcontainers/proxy/vendor/github.com/containers/virtcontainers/pkg/hyperstart.(*Hyperstart).WaitForReady(0xc4203d9d80, 0x1, 0x11)
00:09:04.270 	/home/jenkins/go/src/github.com/clearcontainers/proxy/vendor/github.com/containers/virtcontainers/pkg/hyperstart/hyperstart.go:462 +0x11e
00:09:04.270 github.com/clearcontainers/proxy.(*vm).Connect(0xc4202ae690, 0x1, 0x11)
00:09:04.270 	github.com/clearcontainers/proxy/_test/_obj_test/vm.go:296 +0x138
00:09:04.270 github.com/clearcontainers/proxy.registerVM(0xc4200d9050, 0x8a, 0x8a, 0x90a580, 0xc4203c4640, 0xc4203f2240)
00:09:04.270 	github.com/clearcontainers/proxy/_test/_obj_test/proxy.go:244 +0x6f6
00:09:04.270 github.com/clearcontainers/proxy.(*protocol).handleCommand(0xc4202eb680, 0xc4202c7e98, 0xc4203c4690, 0x0)
00:09:04.270 	github.com/clearcontainers/proxy/_test/_obj_test/protocol.go:129 +0x1fb
00:09:04.270 github.com/clearcontainers/proxy.(*protocol).Serve(0xc4202eb680, 0xbc5340, 0xc42015c3b8, 0x90a580, 0xc4203c4640, 0xc4203c2370, 0xc42021ef88)
00:09:04.270 	github.com/clearcontainers/proxy/_test/_obj_test/protocol.go:200 +0x390
00:09:04.270 github.com/clearcontainers/proxy.(*proxy).serveNewClient(0xc4203ea280, 0xc4202eb680, 0xbc5340, 0xc42015c3b8)
00:09:04.270 	github.com/clearcontainers/proxy/_test/_obj_test/proxy.go:749 +0x1a8
00:09:04.270 github.com/clearcontainers/proxy.(*testRig).ServeNewClient.func1(0xc42034d340, 0xc42015c3b8)
00:09:04.270 	/home/jenkins/go/src/github.com/clearcontainers/proxy/proxy_test.go:162 +0x84
00:09:04.270 created by github.com/clearcontainers/proxy.(*testRig).ServeNewClient
00:09:04.270 	/home/jenkins/go/src/github.com/clearcontainers/proxy/proxy_test.go:164 +0x218
00:09:04.272 exit status 2
00:09:04.272 FAIL	github.com/clearcontainers/proxy	2.087s
```

**Comment by jodh-intel** [comment]
This sounds similar to https://github.com/clearcontainers/runtime/pull/618 where we had to increase the runtime's unit-test timeout under Jenkins.

**Comment by jcvenegas** [comment]
@jodh-intel let me give it a try

**Comment by jcvenegas** [comment]
hit https://github.com/clearcontainers/runtime/issues/622

```
00:16:40.497 not ok 16 ctr execsync std{out,err}
00:16:40.501 # (in test file crio.bats, line 622)
00:16:40.506 #   `[ "$status" -eq 0 ]' failed
00:16:40.508 # 0
00:16:40.508 # time="2017-09-27 15:39:45.084800437Z" level=debug msg="[graphdriver] trying provided driver "aufs"" 
00:16:40.508 # time="2017-09-27 15:39:45.090753103Z" level=info msg="CNI network crionet (type=bridge) is used from /tmp/tmp.iNYRWFWnaY/cni/net.d/10-crio.conf" 
00:16:40.508 # time="2017-09-27 15:39:45.090944302Z" level=info msg="CNI network crionet (type=bridge) is used from /tmp/tmp.iNYRWFWnaY/cni/net.d/10-crio.conf" 
00:16:40.508 # time="2017-09-27 15:39:45.099257353Z" level=debug msg="Golang's threads limit set to 115110" 
00:16:40.508 # time="2017-09-27 15:39:45.100341747Z" level=debug msg="sandboxes: []" 
00:16:40.509 # time="2017-09-27 15:39:45.100676045Z" level=error msg="Failed to start streaming server: listen tcp 10.0.0.4:10010: bind: address already in use" 
00:16:40.509 # time="2017-09-27 15:39:46.230187199Z" level=debug msg="ImageStatusRequest: &ImageStatusRequest{Image:&ImageSpec{Image:redis:alpine,},}" 
00:16:40.509 # time="2017-09-27 15:39:46.230356899Z" level=debug msg="parsed reference into "[aufs@/tmp/tmp.iNYRWFWnaY/crio+/tmp/tmp.iNYRWFWnaY/crio-run]docker.io/library/redis:alpine"" 
00:16:40.509 # time="2017-09-27 15:39:46.231719691Z" level=debug msg="ImageStatusResponse: &ImageStatusResponse{Image:&Image{Id:dd6245165e9b82aa39a453472158405e95c91da16db62757f8d1fb4e43118a96,RepoTags:[docker.io/library/redis:alpine redis:alpine],RepoDigests:[],Size_:27500208,Uid:nil,Username:,},}" 
00:16:40.509 # time="2017-09-27 15:39:46.304956666Z" level=debug msg="ImageStatusRequest: &ImageStatusRequest{Image:&ImageSpec{Image:redis:alpine,},}" 
00:16:40.509 # time="2017-09-27 15:39:46.305052166Z" level=debug msg="parsed reference into "[aufs@/tmp/tmp.iNYRWFWnaY/crio+/tmp/tmp.iNYRWFWnaY/crio-run]docker.io/library/redis:alpine"" 
00:16:40.509 # time="2017-09-27 15:39:46.305361064Z" level=debug msg="ImageStatusResponse: &ImageStatusResponse{Image:&Image{Id:dd6245165e9b82aa39a453472158405e95c91da16db62757f8d1fb4e43118a96,RepoTags:[docker.io/library/redis:alpine redis:alpine],RepoDigests:[],Size_:27500208,Uid:nil,Username:,},}" 
00:16:40.509 # time="2017-09-27 15:39:46.365127918Z" level=debug msg="ImageStatusRequest: &ImageStatusRequest{Image:&ImageSpec{Image:mrunalp/oom,},}" 
00:16:40.509 # time="2017-09-27 15:39:46.365293817Z" level=debug msg="parsed reference into "[aufs@/tmp/tmp.iNYRWFWnaY/crio+/tmp/tmp.iNYRWFWnaY/crio-run]docker.io/mrunalp/oom:latest"" 
00:16:40.509 # time="2017-09-27 15:39:46.365532015Z" level=debug msg="ImageStatusResponse: &ImageStatusResponse{Image:&Image{Id:38f60bbb34b0193f258cae850c962c74c4160be587b61c548672ee6caae12a24,RepoTags:[docker.io/mrunalp/oom:latest mrunalp/oom docker.io/library/mrunalp/oom],RepoDigests:[],Size_:5719481,Uid:nil,Username:,},}" 
00:16:40.509 # time="2017-09-27 15:39:46.429641844Z" level=debug msg="ImageStatusRequest: &ImageStatusRequest{Image:&ImageSpec{Image:redis@sha256:03789f402b2ecfb98184bf128d180f398f81c63364948ff1454583b02442f73b,},}" 
00:16:40.509 # time="2017-09-27 15:39:46.429749443Z" level=debug msg="parsed reference into "[aufs@/tmp/tmp.iNYRWFWnaY/crio+/tmp/tmp.iNYRWFWnaY/crio-run]docker.io/library/redis:latest@03789f402b2ecfb98184bf128d180f398f81c63364948ff1454583b02442f73b"" 
00:16:40.509 # time="2017-09-27 15:39:46.430104841Z" level=debug msg="ImageStatusResponse: &ImageStatusResponse{Image:&Image{Id:03789f402b2ecfb98184bf128d180f398f81c63364948ff1454583b02442f73b,RepoTags:[docker.io/library/redis:latest redis@sha256:03789f402b2ecfb98184bf128d180f398f81c63364948ff1454583b02442f73b docker.io/library/redis@sha256:03789f402b2ecfb98184bf128d180f398f81c63364948ff1454583b02442f73b],RepoDigests:[],Size_:19826844,Uid:nil,Username:,},}" 
00:16:40.509 # time="2017-09-27 15:39:46.493388174Z" level=debug msg="ImageStatusRequest: &ImageStatusRequest{Image:&ImageSpec{Image:runcom/stderr-test,},}" 
00:16:40.509 # time="2017-09-27 15:39:46.493491674Z" level=debug msg="parsed reference into "[aufs@/tmp/tmp.iNYRWFWnaY/crio+/tmp/tmp.iNYRWFWnaY/crio-run]docker.io/runcom/stderr-test:latest"" 
```

**Pull request merged**
