### PR TITLE
CI: Don't require an issue for release PRs

### LINKED ISSUE #202: Don't require an issue for release PRs
Change the `checkcommits` config to not require an issue for release PRs.

### PR DESCRIPTION
**Pull request by jodh-intel**
Change the `checkcommits` config to not require an issue for release
PRs.

Fixes #202.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by jcvenegas** [comment]
lgtm

**Comment by jodh-intel** [comment]
Another repo I dont have perms on. @grahamwhaley, @amshinde - could you take a look please?

**Comment by grahamwhaley** [comment]
we would appear to be waiting on the CIs?

**Comment by jodh-intel** [comment]
We have the green light^Wbutton. Without tape! Merging...

**Pull request merged**
